apiVersion: apps/v1 
kind: Deployment
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: iris
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - image: leblancisc/irishealth-arm64:2020.4.0.524.0
        name: iris
        env:
        - name: ISC_DATA_DIRECTORY
          value: /external/iris
        - name: ISC_CPF_MERGE_FILE
          value: /external/merge/merge.cpf
        ports:
        - containerPort: 52773
          name: smp-http
        volumeMounts:
        - name: iris-external-sys
          mountPath: /external
        - name: cpf-merge
          mountPath: /external/merge
        - name: license
          mountPath: /external/iris.key
          subMount: iris.key
        livenessProbe:
          initialDelaySeconds: 25
          periodSeconds: 10
          exec:
            command:
            - /bin/sh
            - -c
            - "iris qlist iris | grep running"
      volumes:
      - name: iris-external-sys
        persistentVolumeClaim:
          claimName: iris-pvc
      - name: cpf-merge
        configMap:
          name: iris-cpf-merge
      - name: license
        configMap:
          name: iris-license
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-pvc
spec:
  # to install Longhorn use:
  #  kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
  #storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-cpf-merge
  namespace: default
data:
  merge.cpf: |-
    [config]
    globals=0,0,800,0,0,0
    gmheap=256000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-license
  namespace: default
data:
  iris.key: |-
    [ConfigFile]
    FileType=InterSystems License Rev-A.1
    LicenseID=654321

    [License]
    LicenseCapacity=InterSystems IRIS for Health 2020.2, Enterprise:64, Concurrent User, Container(Ubuntu ARM-64)
    CustomerName=Preview Key
    OrderNumber=54321
    ExpirationDate=5/23/2021
    AuthorizationKey=412720000640000640000000000A3F2BA8F093221F18003
    MachineID=


    [License Characteristics]
    Licensed Product: Enterprise
    Licensed Type: Concurrent User
    Licensed Platform: Container(Ubuntu ARM-64)
    Users licensed: 64
    Designation: Field Test
    Multi_Server=enabled
    HealthShare=enabled
    HealthShare_Core=enabled
    IntegratedML=enabled
---
apiVersion: v1
kind: Service
metadata:
  name: iris-svc
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 52773
      targetPort: 52773