apiVersion: apps/v1 
kind: Deployment
metadata:
  name: iris
spec:
  selector:
    matchLabels:
      app: iris
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: iris
    spec:
      containers:
      - image: leblancisc/irishealth-arm64:2020.4.0.524.0
        name: iris
        env:
        - name: ISC_DATA_DIRECTORY
          value: /external/iris
        - name: ISC_CPF_MERGE_FILE
          value: /external/merge/merge.cpf
        ports:
        - containerPort: 52773
          name: smp-http
        volumeMounts:
        - name: iris-external-sys
          mountPath: /external
        - name: cpf-merge
          mountPath: /external/merge
        - name: license
          mountPath: /external/iris.key
          subPath: iris.key
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        livenessProbe:
          initialDelaySeconds: 25
          periodSeconds: 10
          exec:
            command:
            - /bin/sh
            - -c
            - "iris qlist iris | grep running"
      volumes:
      - name: iris-external-sys
        persistentVolumeClaim:
          claimName: iris-pvc
      - name: cpf-merge
        configMap:
          name: iris-cpf-merge
      - name: license
        configMap:
          name: iris-license
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: iris-pvc
spec:
  # to install Longhorn use:
  #  kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-cpf-merge
  namespace: default
data:
  merge.cpf: |-
    [config]
    globals=0,0,800,0,0,0
    gmheap=256000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-license
  namespace: default
data:
  iris.key: |-
    [ConfigFile]
    FileType=InterSystems License Rev-A.1
    LicenseID=654321

    [License]
    LicenseCapacity=InterSystems IRIS for Health 2020.2, Enterprise:64, Concurrent User, Container(Ubuntu ARM-64)
    CustomerName=Preview Key
    OrderNumber=54321
    ExpirationDate=5/23/2021
    AuthorizationKey=412720000640000640000000000A3F2BA8F093221F18003
    MachineID=


    [License Characteristics]
    Licensed Product: Enterprise
    Licensed Type: Concurrent User
    Licensed Platform: Container(Ubuntu ARM-64)
    Users licensed: 64
    Designation: Field Test
    Multi_Server=enabled
    HealthShare=enabled
    HealthShare_Core=enabled
    IntegratedML=enabled
---
apiVersion: v1
kind: Service
metadata:
  name: iris-svc
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
    - protocol: TCP
      port: 52773
      targetPort: 52773
    - name: 47001
      protocol: TCP
      port: 47001
      targetPort: 47001
    - name: 47002
      protocol: TCP
      port: 47002
      targetPort: 47002
    - name: 47003
      protocol: TCP
      port: 47003
      targetPort: 47003
    - name: 47004
      protocol: TCP
      port: 47004
      targetPort: 47004
    - name: 47005
      protocol: TCP
      port: 47005
      targetPort: 47005
    - name: 47006
      protocol: TCP
      port: 47006
      targetPort: 47006
    - name: 47006
      protocol: TCP
      port: 47006
      targetPort: 47006
    - name: 47007
      protocol: TCP
      port: 47007
      targetPort: 47007
    - name: 47008
      protocol: TCP
      port: 47008
      targetPort: 47008
    - name: 47009
      protocol: TCP
      port: 47009
      targetPort: 47009
    - name: 47010
      protocol: TCP
      port: 47010
      targetPort: 47010
    - name: 47011
      protocol: TCP
      port: 47011
      targetPort: 47011
    - name: 47012
      protocol: TCP
      port: 47012
      targetPort: 47012
    - name: 47013
      protocol: TCP
      port: 47013
      targetPort: 47013
    - name: 47014
      protocol: TCP
      port: 47014
      targetPort: 47014
    - name: 47015
      protocol: TCP
      port: 47015
      targetPort: 47015
    - name: 47016
      protocol: TCP
      port: 47016
      targetPort: 47016
    